import { NextRequest, NextResponse } from "next/server";
import {
  getTrades,
  inferTokenAmount,
  saveTrade,
  type StoredTrade,
} from "@/lib/devnet-market";
import { recordCreatorReward } from "@/lib/creator-rewards";

export const dynamic = "force-dynamic";

type Context = {
  params: Promise<{ mint: string }>;
};

type TradeRequest = {
  wallet?: string;
  signature?: string;
  signatures?: string[];
  side?: "buy" | "sell";
  solAmount?: number;
};

export async function GET(
  _request: NextRequest,
  context: Context,
) {
  try {
    const { mint } = await context.params;
    const trades = await getTrades(mint);

    return NextResponse.json({
      mint,
      trades: [...trades].reverse().slice(0, 100),
    });
  } catch (error) {
    return NextResponse.json(
      {
        error:
          error instanceof Error
            ? error.message
            : "Unable to load trades.",
      },
      { status: 500 },
    );
  }
}

export async function POST(
  request: NextRequest,
  context: Context,
) {
  try {
    const { mint } = await context.params;
    const body = (await request.json()) as TradeRequest;

    const wallet = body.wallet?.trim() ?? "";
    const side = body.side ?? "buy";
    const solAmount = Number(body.solAmount);

    const candidateSignatures = Array.from(
      new Set(
        [
          ...(Array.isArray(body.signatures) ? body.signatures : []),
          body.signature,
        ]
          .filter(
            (value): value is string =>
              typeof value === "string" &&
              value.trim().length >= 64,
          )
          .map((value) => value.trim()),
      ),
    );

    if (
      !wallet ||
      candidateSignatures.length === 0 ||
      !Number.isFinite(solAmount) ||
      solAmount <= 0
    ) {
      return NextResponse.json(
        {
          error:
            "wallet, at least one transaction signature, and a positive solAmount are required.",
        },
        { status: 400 },
      );
    }

    const existingTrades = await getTrades(mint);

    const existing = existingTrades.find((trade) =>
      candidateSignatures.includes(trade.signature),
    );

    if (existing) {
      return NextResponse.json({
        ok: true,
        duplicate: true,
        trade: existing,
      });
    }

    let selectedSignature = "";
    let inferredTokenAmount = 0;
    let inferredTimestamp = Math.floor(Date.now() / 1000);

    for (const signature of candidateSignatures) {
      try {
        const inferred = await inferTokenAmount(
          signature,
          mint,
          wallet,
        );

        if (
          Number.isFinite(inferred.tokenAmount) &&
          inferred.tokenAmount > 0
        ) {
          selectedSignature = signature;
          inferredTokenAmount = inferred.tokenAmount;
          inferredTimestamp = inferred.timestamp;
          break;
        }
      } catch {
        // Try the next transaction generated by the launch.
      }
    }

    if (!selectedSignature || inferredTokenAmount <= 0) {
      return NextResponse.json(
        {
          error:
            "The launch was confirmed, but none of its transactions exposed the creator token balance change yet. Retry shortly.",
          retryable: true,
        },
        { status: 409 },
      );
    }

    const priceSol = solAmount / inferredTokenAmount;

    if (!Number.isFinite(priceSol) || priceSol <= 0) {
      return NextResponse.json(
        {
          error:
            "The creator buy price could not be calculated from the confirmed transaction.",
        },
        { status: 422 },
      );
    }

    const trade: StoredTrade = {
      mint,
      wallet,
      signature: selectedSignature,
      side,
      solAmount,
      tokenAmount: inferredTokenAmount,
      priceSol,
      timestamp: inferredTimestamp,
    };

    await saveTrade(trade);

    try {
      await recordCreatorReward(trade);
    } catch (rewardError) {
      console.error(
        "Creator reward ledger write failed:",
        rewardError,
      );
    }

    return NextResponse.json({
      ok: true,
      duplicate: false,
      trade,
    });
  } catch (error) {
    return NextResponse.json(
      {
        error:
          error instanceof Error
            ? error.message
            : "Unable to record trade.",
      },
      { status: 500 },
    );
  }
}
